#!/usr/bin/env python3
"""Retarget a recorded Bench2Dex episode onto a DIFFERENT embodiment.

Why
---
Bench2Dex crosses neither tasks nor embodiments ("tasks and embodiments are not
factorially crossed"), so the same task cannot currently be evaluated on two hands.
This script produces exactly that crossed data by retargeting a recorded joint
trajectory through the repo's own unified state/action space
(`policy/GR00T_XE/ik_arm_converter.XEStateActionConverter`):

    qpos_src --qpos_to_unified--> unified 64-D --unified_to_joint_action--> qpos_tgt
             (arm EE poses + 22 hand semantic slots per hand)

and then writes a copy of the episode whose metadata names the TARGET robot, so the
stock `replay.py` rebuilds the same scene with the new hand and re-captures RGB/tactile.

Scope / honest limits
---------------------
* The unified space stores EE poses in EACH ROBOT'S OWN BASE FRAME, so retargeting
  across different ARMS does not converge (measured: residual 0.7-2.6 m). It works
  within an arm family. Bench2Dex's families:
      UR5   : rh56dfx, rh5dg2, schunk, shadow, wuji   (5 hands)
      Panda : orca, allegro
      xArm7 : ability, leap
  Arm is held constant, which also removes the arm as a confound for a
  cross-HAND study.
* The retargeted motion is kinematically valid but not physically re-planned: a hand
  with fewer/more DoF may not achieve the same grasp. Whether the task still
  completes is measured afterwards by the benchmark evaluator, not assumed.

Usage:
    python 96_retarget_episode.py --src <episode.hdf5> --dst-robot multi_ur5_wuji_with_flange \
        --out <out.hdf5> [--max-frames N]
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np

REPO = Path("/home/wangrenpeng/bench2dex/Bench2Dex")
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "policy" / "GR00T_XE"))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--dst-robot", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--max-frames", type=int, default=0, help="0 = all")
    args = ap.parse_args()

    import h5py
    from ik_arm_converter import XEStateActionConverter, get_ik_failure_stats
    from robots.active_dof_utils import get_active_dof_info

    with h5py.File(args.src, "r") as f:
        src_robot = f["meta/robot_key"][()].decode()
        qpos = np.asarray(f["robot/qpos"][:], np.float64)
        src_names = [n.decode() if isinstance(n, bytes) else str(n)
                     for n in f["robot/joint_names"][:]]
    T = len(qpos) if not args.max_frames else min(len(qpos), args.max_frames)

    src_adi = get_active_dof_info(src_robot)
    dst_adi = get_active_dof_info(args.dst_robot)
    print(f"   src robot : {src_robot}  dof={src_adi.full_dof}")
    print(f"   dst robot : {args.dst_robot}  dof={dst_adi.full_dof}")
    print(f"   frames    : {T}")

    conv = XEStateActionConverter()
    before = dict(get_ik_failure_stats())
    q = np.zeros(dst_adi.full_dof, np.float64)
    out = np.zeros((T, dst_adi.full_dof), np.float64)
    for t in range(T):
        u = conv.qpos_to_unified(qpos[t], src_robot)
        q = np.asarray(conv.unified_to_joint_action(u, args.dst_robot, q)).ravel()
        out[t] = q
    after = get_ik_failure_stats()
    new_fail = {k: v - before.get(k, 0) for k, v in after.items() if v - before.get(k, 0) > 0}
    total_fail = sum(new_fail.values())
    print(f"   IK failures: {total_fail} / {2 * T} arm-frame solves  "
          f"({'OK' if total_fail == 0 else 'WARNING'})")
    if new_fail:
        for k, v in sorted(new_fail.items()):
            print(f"      {k}: {v}")

    # ---- write the retargeted episode -------------------------------------
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    with h5py.File(args.src, "r") as src, h5py.File(args.out, "w") as dst:
        for k in src.keys():
            if k in ("robot",):
                continue
            src.copy(k, dst)
        rg = dst.create_group("robot")
        rg.create_dataset("joint_names",
                          data=np.array(dst_adi.full_joint_names, dtype=object),
                          dtype=h5py.special_dtype(vlen=str))
        rg.create_dataset("qpos", data=out.astype(np.float32),
                          compression="gzip", compression_opts=4)
        rg.create_dataset("qvel", data=np.zeros_like(out, np.float32),
                          compression="gzip", compression_opts=4)
        rg.create_dataset("qeffort", data=np.zeros_like(out, np.float32),
                          compression="gzip", compression_opts=4)
        # tactile groups are regenerated by replay.py; carry an empty placeholder so
        # downstream readers do not see a stale source-hand schema
        tg = rg.create_group("tactile")
        tg.create_group("tacmap")
        tg.create_group("contact_mask")
        tg.create_group("distance_along_normal_m")
        # metadata: point at the target robot
        for key, val in (("meta/robot_key", args.dst_robot),
                         ("meta/frame_count", T)):
            if key in dst:
                del dst[key]
            dst.create_dataset(key, data=val)
        for key in ("meta/action_dim",):
            if key in dst:
                del dst[key]
            dst.create_dataset(key, data=dst_adi.full_dof)
    print(f"   wrote {args.out}")
    return 0 if total_fail == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
